### ISSUE TITLE
iot config route service missing auth checks

### ISSUE THREAD

**Issue by ederuiter** [helium/oracles#364]
It seems a couple of endpoint in the iot_config route service are missing signature checks:
The request messages include the signature field, but it is not verified by the implementation

- get_euis
- update_euis
- delete_euis
- get_devaddr_ranges
- update_devaddr_ranges
- delete_devaddr_ranges

The actual security implications do not seem very high as you still need the `route.id` which is a uuid. But as it is a V1 uuid it is not that secure and should definitively not be used as the only security measure.

Also the create method has security issues:
You can create a route with a different oui than the one you are authenticated with

```
{
  "oui": <your oui>,
  "signature": <your signature>,
  "route": {
     "oui": <other oui>,
     ..
   }
}
```

Another minor thing: the update method correctly checks against `route.oui` instead of `request.oui`, but it can lead to developer confusion if you accidentally supply a different `request.oui`. Ideally the code should make sure `request.oui == route.oui` instead of ignoring it.

**Comment by jeffgrunewald** [comment]
Good eye noticing the incomplete auth verification on some of these route @ederuiter , but these are the result of very recent changes to the config service api and not intended to be functionally complete or running anywhere outside an alpha testing environment at this point; due to a number of conflicting priorities the work on these new streaming methods is still in progress. 

 With that in mind, I don’t see any reason anyone would want to create a route under a different oui than one they control since they would be unable to attach any devaddr ranges, eui pairs or session key filters once those associated auth checks are in place, but it would be really easy to validate `request.oui == request.route.oui` so I’ll make a note to add that. 
 
For that matter, the config service is still enough in flux that we haven’t formally locked down the initial schema of the `iot_config.proto` so we have time to decide whether or not there’s value in having the oui attached to the create route request at both the top level _and_ the route level or just reading it from the route level and collapsing the create and update requests into a single message

**Comment by jeffgrunewald** [comment]
This should be fully addressed by https://github.com/helium/oracles/pull/394; once this is merged shortly I believe we should be able to close this issue out.

**Comment by ederuiter** [comment]
@jeffgrunewald Sorry, I did not have time to look at it earlier. But this certainly looks a lot better!

I do however still see a couple of issues in the streaming update methods: `route_service.update_euis` /  `route_service.update_devaddr_ranges` / `session_key_service.update`
- the authorization check is only done for the first message received; if the next messages contain updates with a different route/org this is allowed. The easiest solution is to force all subsequent messages to have the same route/org
- as all the deletes / inserts are applied after the last message is received, I think it would be good to have a strict maximum number of updates per stream to prevent out-of-memory conditions / big database transactions that could cause latency spikes
- as all the inserts are applied before all the deletes, it could potentially lead to duplicate key errors and differences in how the client expects the final result to be. The easy solution is to not allow multiple updates to the same pair.

An example of the last issue for update_euis:

If the database already contains a eui pair for the route R: (R, AA, AA) and you would send 2 updates in a single stream:
- DELETE (R, AA, AA)
- INSERT (R, AA, AA)

From the client's perspective nothing should have changed, but instead the insert would cause a duplicate key error

Another case: if the database does not contain eui pairs for route R and you would send the same 2 updates as stated above in a single stream.
From the clients perspective it should delete a record that does not exist, so nothing should happen and then it should insert a new record .. but as all the deletes are done after the inserts the record is first inserted and then deleted again.

**Comment by jeffgrunewald** [comment]
Thanks for taking a look:

> the authorization check is only done for the first message received; if the next messages contain updates with a different route/org this is allowed

I'm not sure this was the intention the Router team had when they decided on this API but I think it's reasonable to expect to update one router/RPC call at a time. I agree the ability for route_ids/ouis to bleed across orgs in this manner is not desirable but from an "auth" perspective I think we can continue to perform the signature authorization on the first message and then ID match on subsequent messages only; the goal being to avoid performing an expensive crypto operation on every message in a potentially very large set. If it's feasible to inject messages into an established grpc stream this would be a bigger problem to address but I don't know if that's a feasible attack vector

> as all the deletes / inserts are applied after the last message is received, I think it would be good to have a strict maximum number of updates per stream

I'll have to confer with the Router team on this one; they wanted to ensure all updates were applied atomically which is why these inserts are explicitly _not_ batch-inserted at the moment and avoiding that allows all desired updates to be applied without the config service having to track the state of an update stream. 

For the last issue, our intention behind the route management is to be as permissive on the config service side as we can within the bounds of an orgs constraints and push responsibility of a lot of that "correctness" management to the operator so we avoid the config service having to track the in-progress state of very large record updates. The database already considers the triples `(route_id, app_eui, dev_eui)` and `(route_id, start_devaddr, end_devaddr)` to be unique primary keys so any _other_ combination of the same values in a set of updates would be allowed and only a single instance of each triple is allowed. that would lead to the question: "why as an operator would anyone want to delete and insert the exact same eui pair in the same update operation?" and I think in a case like that's it's reasonable to expect the org to manage their own routes that way.

Let me add the additional checks for the first issue and discuss with the team how we want to handle the second one and if we still think we don't want the responsibility for maintaining correctness of the third type of scenario and go from there

**Comment by ederuiter** [comment]
👌 As long as the behaviour is properly documented I don't see any problems with it. But right now, without any documentation, this is not the behaviour I'd expect.
Also the behaviour of applying the updates after the stream has closed should be documented.

For the limit on number of updates in a single stream: I was thinking about preventing abuse of the api; keeping the stream open and slowly adding more updates over time would eventually lead to a dos situation.
This also ties in with the documentation; in the first iteration of my [library](https://github.com/thisisdevelopment/helium-route-updater) I tried to keep the stream open and push a message whenever a device was added/removed .. so in order to prevent that situation; it would be good to have have either a max number of messages, or a max duration/idle time of the stream.

**Comment by jeffgrunewald** [comment]
so in the interest of avoiding over-optimization at the cost of security i've shifted my view and in https://github.com/helium/oracles/pull/404 included some more comprehensive validations of incoming updates:
- checking signatures of ALL incoming update messages
- checking the devaddr for session key filters and the devaddr range for routes fall within the org's bounding devaddr constraints
- checking session key filters' attached OUI matches the authorizing OUI of the signer and the Route ID for EUI pairs and DevAddr Ranges matches a Route ID owned by the authorizing signer
- Batching database persistence of large streaming update requests to provide the capability of partial updates and avoid the Config Service running out of memory. If there's a failure of the update stream at any point is still the responsibility of the calling client to figure out where they left off in the update to avoid duplicate request
- To that end, the validations against all update request messages should return to the caller the specific failing request that triggered the stream to fail if a failure occurs.
